apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsi-agent.fullname" . }}
  labels:
    {{- include "opsi-agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "opsi-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "opsi-agent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "opsi-agent.fullname" . }}
              key: OPENAI_API_KEY
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          timeoutSeconds: 1
          periodSeconds: 3
          initialDelaySeconds: 30
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          timeoutSeconds: 1
          periodSeconds: 5
          initialDelaySeconds: 30
          successThreshold: 1
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 3
          initialDelaySeconds: 30
          successThreshold: 1
          failureThreshold: 50
