apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsi-agent.fullname" . }}
  labels:
    {{- include "opsi-agent.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.openai_api_key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsi-agent.fullname" . }}-postgres
  labels:
    {{- include "opsi-agent-postgres.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
