apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsi-agent.fullname" . }}
  labels:
    {{- include "opsi-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "opsi-agent.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsi-agent.fullname" . }}-postgres
  labels:
    {{- include "opsi-agent-postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "opsi-agent-postgres.selectorLabels" . | nindent 4 }}
